name: filmhead
favicon: null
layout_spectrum: 0.58614
typography_spectrum: 0.39103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ccd3cc'
    - '#4e3c3c'
    - '#91a9ad'
    - '#6e8c8c'
    - '#967266'
  brandStrength: 0
  lightness: 0.6998411333188415
  saturation: 0.9239028913434595
  rhythmicContrast: 0.9140834112185985
purpose: []
